module.exports = {
  idle: ["fruit", "water", "wood", "iron", "herbs", "rations", "drinking_water", "potions"],

  capacities: {
    fruit: 500,
    water: 500,
    wood: 500,
    iron: 500,
    herbs: 500,
    rations: 500,
    drinking_water: 500,
    potions: 200,
  },

  perTick: {
    fruit: 3,
    water: 3,
    wood: 3,
    iron: 3,
    herbs: 3,
    rations: 2,
    drinking_water: 2,
    potions: 1,
  },

  // Crafting recipes - keys must match items.js item names exactly
  recipes: {
    "Small Healing Potion": { herbs: 5, water: 3, price: 30 },
    "Large Healing Potion": { herbs: 15, water: 10, price: 80 },
    "Mana Potion": { herbs: 10, water: 5, magic_stone: 1, price: 100 },
    "Iron Sword": { iron: 20, wood: 10, price: 100 },
    "Steel Sword": { iron: 40, wood: 15, price: 200 },
    "Magic Staff": { iron: 15, herbs: 20, price: 180 },
    "Battle Axe": { iron: 35, wood: 20, price: 180 },
    "Longbow": { wood: 30, herbs: 10, price: 150 },
    "Dagger": { iron: 10, wood: 5, price: 60 },
    "Warhammer": { iron: 50, wood: 25, price: 250 },
    "Crystal Wand": { iron: 10, herbs: 40, magic_stone: 5, price: 350 },
    "Leather Armor": { herbs: 15, price: 80 },
    "Iron Armor": { iron: 30, wood: 15, price: 150 },
    "Steel Armor": { iron: 60, wood: 25, price: 300 },
    "Chain Mail": { iron: 45, herbs: 10, price: 220 },
    "Plate Armor": { iron: 80, wood: 20, magic_stone: 5, price: 400 },
    "Mage Robes": { herbs: 30, water: 20, price: 160 },
    "Iron Helmet": { iron: 20, price: 80 },
    "Steel Helmet": { iron: 35, price: 140 },
    "Wizard Hat": { herbs: 20, magic_stone: 2, price: 120 },
    "Knight Helm": { iron: 40, wood: 10, price: 180 },
    "Health Pendant": { herbs: 25, price: 120 },
    "Power Ring": { iron: 15, price: 100 },
    "Defense Ring": { iron: 20, price: 120 },
    "Magic Pendant": { herbs: 30, magic_stone: 3, price: 200 },
    "Shield Amulet": { iron: 25, herbs: 15, price: 150 },
    "Lucky Charm": { magic_stone: 5, price: 180 },
  },
};
